# -*- coding: utf-8 -*-
"""IMIB Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/163M8gCzVkM9V-bBqYLUeL_oTj8SIjkIz

## Assignment 2B: Data Visualization & Insight Storytelling

I will now attempt to load your dataset. Since you mentioned it could be either CSV or Excel, I'll try to load it as a CSV first, and if that fails, I'll try loading it as an Excel file. I'll then display the dataset's shape, column names, data types, and the first five rows.
"""

import pandas as pd

# The user provided the file '/content/global_climate_energy_2020_2024.csv'
file_path = '/content/global_climate_energy_2020_2024.csv'

df = None

try:
    df = pd.read_csv(file_path)
    print(f"Successfully loaded '{file_path}'")
except Exception as e:
    print(f"Failed to load '{file_path}': {e}")

if df is None:
    print("Error: Failed to load the dataset. Please check the file path and format.")
else:
    print("\n--- Dataset Information ---")
    print(f"Dataset shape: {df.shape}")
    print("\nColumn names:")
    print(df.columns.tolist())
    print("\nData types:")
    print(df.info())
    print("\nFirst five rows:")
    display(df.head())

"""### Chart 1: CO2 Emission Trend Over Time"""

import matplotlib.pyplot as plt
import seaborn as sns

# Ensure 'date' column is datetime
df['date'] = pd.to_datetime(df['date'])

# Aggregate CO2 emission by date (sum across all countries for global trend)
daily_co2_emission = df.groupby('date')['co2_emission'].sum().reset_index()

plt.figure(figsize=(12, 6))
sns.lineplot(data=daily_co2_emission, x='date', y='co2_emission')
plt.title('Global Daily CO2 Emission Trend (2020-2024)')
plt.xlabel('Date')
plt.ylabel('Total CO2 Emission (Units)') # Assuming arbitrary units as not specified
plt.grid(True)
plt.tight_layout()
plt.savefig('TrendChart.png')
plt.show()

"""### Chart 2: Total CO2 Emission by Country"""

import matplotlib.pyplot as plt
import seaborn as sns

# Aggregate total CO2 emission by country
country_co2_emission = df.groupby('country')['co2_emission'].sum().reset_index()
country_co2_emission = country_co2_emission.sort_values(by='co2_emission', ascending=False)

plt.figure(figsize=(12, 7))
sns.barplot(data=country_co2_emission, x='co2_emission', y='country', palette='viridis')
plt.title('Total CO2 Emission by Country (2020-2024)')
plt.xlabel('Total CO2 Emission (Units)')
plt.ylabel('Country')
plt.tight_layout()
plt.savefig('ComparisonChart.png')
plt.show()

"""### Chart 3: Distribution of Energy Price"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.histplot(df['energy_price'], bins=30, kde=True)
plt.title('Distribution of Energy Price')
plt.xlabel('Energy Price (Units)') # Assuming arbitrary units as not specified
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.75)
plt.tight_layout()
plt.savefig('DistributionChart.png')
plt.show()

!pip install python-pptx

from pptx import Presentation
from pptx.util import Inches, Pt

prs = Presentation()

# ---------------- Slide 1 ----------------
slide = prs.slides.add_slide(prs.slide_layouts[5])

title = slide.shapes.title
title.text = "Assignment 2B\nData Visualization & Insight Storytelling"

textbox = slide.shapes.add_textbox(Inches(0.8), Inches(1.8), Inches(8), Inches(1))
p = textbox.text_frame.paragraphs[0]
p.text = "Student Name: Akshay Gabrieal"
p.font.size = Pt(24)

# ---------------- Slide 2 ----------------
slide = prs.slides.add_slide(prs.slide_layouts[5])
slide.shapes.title.text = "Trend Chart"

slide.shapes.add_picture(
    "TrendChart.png",
    Inches(0.5),
    Inches(0.8),
    width=Inches(7)
)

textbox = slide.shapes.add_textbox(Inches(7.7), Inches(0.8), Inches(2.2), Inches(5))
tf = textbox.text_frame
tf.text = """Insight

• Daily CO₂ emissions fluctuate significantly between 2020–2024.

• Most values remain between 5,000–12,000 units.

• Monitoring these fluctuations helps identify periods of higher emissions and supports climate planning."""

# ---------------- Slide 3 ----------------
slide = prs.slides.add_slide(prs.slide_layouts[5])
slide.shapes.title.text = "Comparison Chart"

slide.shapes.add_picture(
    "ComparisonChart.png",
    Inches(0.5),
    Inches(0.8),
    width=Inches(7)
)

textbox = slide.shapes.add_textbox(Inches(7.7), Inches(0.8), Inches(2.2), Inches(5))
tf = textbox.text_frame
tf.text = """Insight

• Australia has the highest total CO₂ emissions.

• Turkey records the lowest among the listed countries.

• Countries with higher emissions should be prioritized for sustainability initiatives."""

# ---------------- Slide 4 ----------------
slide = prs.slides.add_slide(prs.slide_layouts[5])
slide.shapes.title.text = "Distribution Chart"

slide.shapes.add_picture(
    "DistributionChart.png",
    Inches(0.5),
    Inches(0.8),
    width=Inches(7)
)

textbox = slide.shapes.add_textbox(Inches(7.7), Inches(0.8), Inches(2.2), Inches(5))
tf = textbox.text_frame
tf.text = """Insight

• Energy prices are broadly distributed.

• No major concentration or extreme outliers are observed.

• Price variation affects energy affordability and sustainability planning."""

# ---------------- Slide 5 ----------------
slide = prs.slides.add_slide(prs.slide_layouts[5])
slide.shapes.title.text = "Narrative"

textbox = slide.shapes.add_textbox(Inches(0.5), Inches(0.8), Inches(8.5), Inches(5))
tf = textbox.text_frame

tf.text = """Problem

Understanding CO₂ emissions and energy patterns is essential for sustainability.

Data

The cleaned dataset contains climate and energy information from 2020–2024.

Insights

• CO₂ emissions fluctuate over time.
• Emissions vary across countries.
• Energy prices differ across observations.

Recommendation

Promote renewable energy, improve energy efficiency, and continuously monitor emissions to support informed environmental decision-making.
"""

prs.save("AkshayGabrieal_DataVisualization.pptx")

print("PowerPoint created successfully!")

"""The PowerPoint presentation has been generated as `AkshayGabrieal_SolutionConcept.pptx`.

Now, I will attempt to convert this `.pptx` file to a `.pdf` file. This often requires an external tool like `unoconv` (which uses LibreOffice). I'll install LibreOffice and `unoconv` if they are not already available in the Colab environment, and then perform the conversion.
"""

# Install LibreOffice and unoconv for PDF conversion
print("Installing LibreOffice and unoconv...")
!apt-get update > /dev/null
!apt-get install -y libreoffice unoconv > /dev/null
print("Installation complete.")

# Convert PPTX to PDF
output_pptx_filename = "AkshayGabrieal_SolutionConcept.pptx"
output_pdf_filename = "AkshayGabrieal_SolutionConcept.pdf"

print(f"Converting {output_pptx_filename} to {output_pdf_filename}...")
!unoconv -f pdf {output_pptx_filename}

# Check if PDF was created
import os
if os.path.exists(output_pdf_filename):
    print(f"Successfully created {output_pdf_filename}")
else:
    print(f"Failed to create {output_pdf_filename}. You may need to manually convert the PPTX file.")

!pip install -q python-pptx pillow

# ==========================================================
# INSTALL LIBRARY
# ==========================================================

!pip -q install python-pptx

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_AUTO_SHAPE_TYPE
from pptx.dml.color import RGBColor

# ----------------------------------------------------------
# CREATE PRESENTATION
# ----------------------------------------------------------

prs = Presentation()

prs.slide_width = Inches(13.33)
prs.slide_height = Inches(7.5)

# ----------------------------------------------------------
# COLORS
# ----------------------------------------------------------

DARK_GREEN = RGBColor(20,90,50)

GREEN = RGBColor(34,139,34)

LIGHT_GREEN = RGBColor(120,200,120)

WHITE = RGBColor(255,255,255)

BLACK = RGBColor(30,30,30)

# ==========================================================
# HELPER FUNCTIONS
# ==========================================================

def add_background(slide):

    fill = slide.background.fill

    fill.solid()

    fill.fore_color.rgb = DARK_GREEN


def add_title(slide,title):

    textbox = slide.shapes.add_textbox(
        Inches(0.5),
        Inches(0.3),
        Inches(12),
        Inches(0.6)
    )

    p = textbox.text_frame.paragraphs[0]

    p.text = title

    p.font.size = Pt(28)

    p.font.bold = True

    p.font.color.rgb = WHITE


def add_footer(slide):

    textbox = slide.shapes.add_textbox(
        Inches(0.5),
        Inches(7.0),
        Inches(12),
        Inches(0.3)
    )

    p = textbox.text_frame.paragraphs[0]

    p.text = "Assignment 3 | Smart Sustainability Solution"

    p.alignment = PP_ALIGN.RIGHT

    p.font.size = Pt(11)

    p.font.color.rgb = WHITE

def add_card(slide,left,top,width,height,title,text):

    shape = slide.shapes.add_shape(

        MSO_AUTO_SHAPE_TYPE.ROUNDED_RECTANGLE,

        left,

        top,

        width,

        height

    )

    shape.fill.solid()

    shape.fill.fore_color.rgb = GREEN

    shape.line.color.rgb = LIGHT_GREEN

    tf = shape.text_frame

    p = tf.paragraphs[0]

    p.text = title

    p.font.size = Pt(18)

    p.font.bold = True

    p.font.color.rgb = WHITE

    p = tf.add_paragraph()

    p.text = text

    p.font.size = Pt(15)

    p.font.color.rgb = WHITE

# ==========================================================
# SLIDE 1
# ==========================================================

slide = prs.slides.add_slide(prs.slide_layouts[6])

add_background(slide)

add_title(slide,"Problem Definition")

add_footer(slide)

problem = """Increasing CO₂ emissions and inefficient energy
consumption continue to contribute to climate
change and environmental degradation.

The climate-energy dataset (2020–2024) shows
changing CO₂ emissions, varying energy prices,
and different emission levels across countries.

Without continuous monitoring, organizations
cannot quickly detect abnormal emissions or
improve energy efficiency."""

add_card(

    slide,

    Inches(0.7),

    Inches(1.1),

    Inches(5.8),

    Inches(4.8),

    "Problem",

    problem

)

importance = """Why it matters

• Climate change is accelerating

• Higher operational costs

• Delayed decision making

• Increased carbon footprint

• Need for sustainable planning"""

add_card(

    slide,

    Inches(6.8),

    Inches(1.1),

    Inches(5.8),

    Inches(4.8),

    "Importance",

    importance

)

prs.save("Test_Part1.pptx")

print("Slide 1 Created Successfully")

# ==========================================================
# SLIDE 2 : SYSTEM DESIGN
# ==========================================================

slide = prs.slides.add_slide(prs.slide_layouts[6])

add_background(slide)

add_title(slide, "System Design")

add_footer(slide)

left_text = """Current System Gaps

• Manual monitoring

• Delayed reporting

• Difficult to detect abnormal emissions

• No predictive analytics

• No automated alerts

• Reactive instead of proactive decision making
"""

add_card(
    slide,
    Inches(0.4),
    Inches(1.1),
    Inches(3.3),
    Inches(5.2),
    "Current System",
    left_text
)

components = [

    "IoT\nSensors",

    "Data\nCollection",

    "Cloud\nStorage",

    "AI\nAnalytics",

    "Dashboard",

    "Alerts"

]

x = 4.3
y = 2.6

box_width = 1.2
box_height = 0.9

boxes = []

for i, name in enumerate(components):

    box = slide.shapes.add_shape(

        MSO_AUTO_SHAPE_TYPE.ROUNDED_RECTANGLE,

        Inches(x + i*1.35),

        Inches(y),

        Inches(box_width),

        Inches(box_height)

    )

    box.fill.solid()

    box.fill.fore_color.rgb = LIGHT_GREEN

    box.line.color.rgb = WHITE

    tf = box.text_frame

    tf.clear()

    p = tf.paragraphs[0]

    p.text = name

    p.font.size = Pt(14)

    p.font.bold = True

    p.font.color.rgb = BLACK

    p.alignment = PP_ALIGN.CENTER

    boxes.append(box)

for i in range(len(boxes)-1):

    x1 = boxes[i].left + boxes[i].width

    y1 = boxes[i].top + boxes[i].height//2

    arrow = slide.shapes.add_shape(

        MSO_AUTO_SHAPE_TYPE.RIGHT_ARROW,

        x1,

        y1-8000,

        18000,

        7000

    )

    arrow.fill.solid()

    arrow.fill.fore_color.rgb = WHITE

    arrow.line.color.rgb = WHITE

solution = """

EcoVision AI

A smart sustainability platform that continuously
collects environmental data from sensors,
stores it in the cloud, analyses it using AI,
and provides real-time dashboards and alerts.

"""

add_card(

    slide,

    Inches(4.4),

    Inches(4.3),

    Inches(7.8),

    Inches(1.7),

    "Proposed Solution",

    solution

)

prs.save("Test_Part2.pptx")

print("Slide 2 Added Successfully")

# ==========================================================
# SLIDE 3 : DATA FLOW
# ==========================================================

slide = prs.slides.add_slide(prs.slide_layouts[6])

add_background(slide)

add_title(slide, "Data Flow")

add_footer(slide)

flow_steps = [

    "Sensors",

    "Data\nCollection",

    "Cloud\nStorage",

    "AI\nAnalysis",

    "Dashboard",

    "Decision\nMakers"

]

start_x = 0.6
start_y = 1.3

box_w = 1.6
box_h = 0.8

gap = 0.35

boxes = []

for i, step in enumerate(flow_steps):

    shape = slide.shapes.add_shape(

        MSO_AUTO_SHAPE_TYPE.ROUNDED_RECTANGLE,

        Inches(start_x+i*(box_w+gap)),

        Inches(start_y),

        Inches(box_w),

        Inches(box_h)

    )

    shape.fill.solid()

    shape.fill.fore_color.rgb = LIGHT_GREEN

    shape.line.color.rgb = WHITE

    tf = shape.text_frame

    tf.clear()

    p = tf.paragraphs[0]

    p.text = step

    p.font.bold = True

    p.font.size = Pt(14)

    p.font.color.rgb = BLACK

    p.alignment = PP_ALIGN.CENTER

    boxes.append(shape)

flow_steps = [

    "Sensors",

    "Data\nCollection",

    "Cloud\nStorage",

    "AI\nAnalysis",

    "Dashboard",

    "Decision\nMakers"

]

start_x = 0.6
start_y = 1.3

box_w = 1.6
box_h = 0.8

gap = 0.35

boxes = []

for i, step in enumerate(flow_steps):

    shape = slide.shapes.add_shape(

        MSO_AUTO_SHAPE_TYPE.ROUNDED_RECTANGLE,

        Inches(start_x+i*(box_w+gap)),

        Inches(start_y),

        Inches(box_w),

        Inches(box_h)

    )

    shape.fill.solid()

    shape.fill.fore_color.rgb = LIGHT_GREEN

    shape.line.color.rgb = WHITE

    tf = shape.text_frame

    tf.clear()

    p = tf.paragraphs[0]

    p.text = step

    p.font.bold = True

    p.font.size = Pt(14)

    p.font.color.rgb = BLACK

    p.alignment = PP_ALIGN.CENTER

    boxes.append(shape)

for i in range(len(boxes)-1):

    arrow = slide.shapes.add_shape(

        MSO_AUTO_SHAPE_TYPE.RIGHT_ARROW,

        boxes[i].left+boxes[i].width,

        boxes[i].top+9000,

        18000,

        5000

    )

    arrow.fill.solid()

    arrow.fill.fore_color.rgb = WHITE

    arrow.line.color.rgb = WHITE

data = """

Collected Data

• CO₂ Emissions

• Energy Consumption

• Temperature

• Humidity

• Renewable Energy Share

"""

add_card(

    slide,

    Inches(0.6),

    Inches(3.0),

    Inches(3.6),

    Inches(2.5),

    "Collected Data",

    data

)

analysis = """

AI Uses Data To

• Detect abnormal emissions

• Predict future trends

• Monitor energy usage

• Generate alerts

"""

add_card(

    slide,

    Inches(4.6),

    Inches(3.0),

    Inches(3.8),

    Inches(2.5),

    "AI Analysis",

    analysis

)

decision = """

Decisions Enabled

• Reduce energy waste

• Improve efficiency

• Support sustainability planning

• Real-time monitoring

"""

add_card(

    slide,

    Inches(8.8),

    Inches(3.0),

    Inches(3.8),

    Inches(2.5),

    "Decision Support",

    decision

)

summary = slide.shapes.add_textbox(

    Inches(0.8),

    Inches(6.0),

    Inches(12),

    Inches(0.5)

)

tf = summary.text_frame

p = tf.paragraphs[0]

p.text = "Smart sensors continuously collect environmental data → AI analyzes the data → Decision makers receive real-time insights and recommendations."

p.font.size = Pt(18)

p.font.bold = True

p.font.color.rgb = WHITE

p.alignment = PP_ALIGN.CENTER

prs.save("Test_Part3.pptx")

print("Slide 3 Created Successfully")

# ==========================================================
# SLIDE 4 : EXPECTED IMPACT
# ==========================================================

slide = prs.slides.add_slide(prs.slide_layouts[6])

add_background(slide)

add_title(slide,"Expected Impact")

add_footer(slide)

environment = """

• Lower CO₂ emissions

• Better air quality

• Reduced carbon footprint

• Increased renewable energy usage

"""

add_card(

    slide,

    Inches(0.5),

    Inches(1.2),

    Inches(3),

    Inches(2.1),

    "Environmental",

    environment

)

economic = """

• Reduced energy costs

• Better resource utilization

• Lower maintenance expenses

• Improved productivity

"""

add_card(

    slide,

    Inches(3.7),

    Inches(1.2),

    Inches(3),

    Inches(2.1),

    "Economic",

    economic

)

social = """

• Cleaner environment

• Improved public health

• Better quality of life

• Sustainable communities

"""

add_card(

    slide,

    Inches(6.9),

    Inches(1.2),

    Inches(3),

    Inches(2.1),

    "Social",

    social

)

operational = """

• Real-time monitoring

• Faster decisions

• AI-based alerts

• Automated reporting

"""

add_card(

    slide,

    Inches(10.1),

    Inches(1.2),

    Inches(2.7),

    Inches(2.1),

    "Operational",

    operational

)

outcomes = """

Expected Outcomes

✔ 15–25% reduction in unnecessary energy consumption

✔ Faster detection of abnormal CO₂ emissions

✔ Improved sustainability reporting

✔ Better renewable energy planning

✔ AI-supported decision making

"""

add_card(

    slide,

    Inches(0.5),

    Inches(3.7),

    Inches(6),

    Inches(2.3),

    "Expected Outcomes",

    outcomes

)

benefits = """

Government

Industries

Educational Institutions

Environmental Organizations

Citizens

Researchers

"""

add_card(

    slide,

    Inches(6.8),

    Inches(3.7),

    Inches(2.8),

    Inches(2.3),

    "Beneficiaries",

    benefits

)

conclusion = """

Conclusion

EcoVision AI enables continuous monitoring of energy usage and CO₂ emissions.
By combining IoT sensors, cloud storage, and AI analytics, the system supports
timely decisions, reduces environmental impact, and promotes sustainable
energy management.

"""

add_card(

    slide,

    Inches(9.8),

    Inches(3.7),

    Inches(2.8),

    Inches(2.3),

    "Conclusion",

    conclusion

)

# ==========================================================
# SAVE PRESENTATION
# ==========================================================

output_file = "AkshayGabrieal_SolutionConcept.pptx"

prs.save(output_file)

print("="*50)
print("Presentation Created Successfully!")
print("="*50)
print(output_file)

from google.colab import files

files.download("AkshayGabrieal_SolutionConcept.pptx")

!pip -q install openpyxl reportlab

import pandas as pd
import numpy as np

from google.colab import files

import matplotlib.pyplot as plt
import seaborn as sns

uploaded = files.upload()

filename = list(uploaded.keys())[0]

if filename.endswith(".csv"):
    df = pd.read_csv(filename)
else:
    df = pd.read_excel(filename)

df.head()

print("="*60)
print("DATASET OVERVIEW")
print("="*60)

print("Rows :",df.shape[0])

print("Columns :",df.shape[1])

print()

print(df.info())

print()

display(df.describe(include='all'))

print("="*60)
print("COLUMN DETAILS")
print("="*60)

for col in df.columns:

    print(col)

    print("Datatype :",df[col].dtype)

    print("Missing :",df[col].isnull().sum())

    print("-"*40)

print(df.isnull().sum())

numeric = df.select_dtypes(include=np.number).columns

categorical = df.select_dtypes(exclude=np.number).columns

for col in numeric:

    df[col] = df[col].fillna(df[col].median())

for col in categorical:

    df[col] = df[col].fillna(df[col].mode()[0])

print("Missing values handled.")

print("Duplicates Before :",df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates After :",df.duplicated().sum())

df.columns = (

    df.columns

      .str.strip()

      .str.lower()

      .str.replace(" ","_")

      .str.replace("-","_")

)

df.head()

output_excel = "AkshayGabrieal_CleanedDataset.xlsx"

df.to_excel(output_excel,index=False)

print("Saved :",output_excel)

display(df.describe())

numeric=df.select_dtypes(include=np.number)

print("Mean Values")

display(numeric.mean())

print()

print("Maximum Values")

display(numeric.max())

print()

print("Minimum Values")

display(numeric.min())

print("="*60)
print("OUTLIERS")
print("="*60)

for col in numeric.columns:

    q1=numeric[col].quantile(0.25)

    q3=numeric[col].quantile(0.75)

    iqr=q3-q1

    lower=q1-1.5*iqr

    upper=q3+1.5*iqr

    outliers=df[(df[col]<lower)|(df[col]>upper)]

    print(col)

    print("Outliers :",len(outliers))

    print("-"*40)

summary=f"""

Assignment 2A
Dataset Cleaning and Exploration

Dataset Overview

The uploaded dataset contains {df.shape[0]} rows and {df.shape[1]} columns related to climate and energy information.

Cleaning Steps

• Checked all missing values.

• Filled numerical missing values using the median.

• Filled categorical missing values using the mode.

• Removed duplicate records.

• Standardized column names using lowercase and underscores.

Key Patterns

1. Numerical values show consistent trends across the dataset.

2. Some variables display noticeable variation between observations.

3. The dataset contains sufficient records for meaningful sustainability analysis.

Anomalies

1. A few observations have unusually high numerical values.

2. Some records lie outside the normal interquartile range.

Assumptions

Missing numerical values were replaced with the median because it is less sensitive to extreme values. Missing categorical values were replaced with the most frequent category. Column names were standardized only for consistency.

Conclusion

The cleaned dataset is consistent, organized and ready for visualization, predictive analysis and sustainability decision making.

"""

print(summary)

from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet

styles=getSampleStyleSheet()

doc=SimpleDocTemplate("AkshayGabrieal_DataSummary.pdf")

story=[]

story.append(Paragraph("<b>Assignment 2A - Dataset Cleaning and Exploration</b>",styles["Title"]))

story.append(Paragraph(summary.replace("\n","<br/>"),styles["BodyText"]))

doc.build(story)

print("PDF Created Successfully")

files.download("AkshayGabrieal_CleanedDataset.xlsx")

files.download("AkshayGabrieal_DataSummary.pdf")